package Vista;

import java.sql.SQLException;

import Controlador.ControladorFactura;

/**
*
* @author JOSE
*/
public class AgregarProducto extends javax.swing.JFrame {

   /**
    * Creates new form AgregarProducto
    */
	private ControladorFactura FacturaC;
   public AgregarProducto() {
       initComponents();
       setSize(600,200);
       FacturaC=new ControladorFactura();
       
       /** AQUI ES DONDE SE LLENA LA LISTA DE PRODUCTOS PERO DONDE ESTA EL GET ESTA UN 1 ES EL
       ESTOY MIRANDO COMO RECORRERLO Y QUE SE LLENE TODA LA LISTA ENTONCES, AGREGA UN ITEM
       DE EL METODO listarproductos DE EL CONTROLADOR Y TIENE UN CONTRO DE EXCEPCIONES PORQUE
       BIENE DEL TIPO DE CONEXION DE SQL.
       Esta en esta parte porque para que se llene el combo box, se llena cuando se inicia la
       ventana.
       
       */
       
       this.jComboBox1_PRODUCTOS.removeAllItems();
	   try {
		   for(int i=0;i<FacturaC.listarproductos().size();i++) {
			this.jComboBox1_PRODUCTOS.addItem(FacturaC.listarproductos().get(i).getNombre());
		   }
		   } catch (SQLException e) {
			// TODO Bloque catch generado automáticamente
			e.printStackTrace();
		}
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jComboBox1_PRODUCTOS = new javax.swing.JComboBox<>();
       jLabel1_PRODUCTO = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jButton1_OK = new javax.swing.JButton();
       jTextField1_CANTIDAD = new javax.swing.JTextField();
       jLabel3_CANTIDAD = new javax.swing.JLabel();
       jButton2_CANCELAR = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jComboBox1_PRODUCTOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       jComboBox1_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox1_PRODUCTOSActionPerformed(evt);
           }
       });

       jLabel1_PRODUCTO.setText("PRODUCTO");

       jLabel2.setText("AGREGAR PRODUCTOS");

       jButton1_OK.setText("OK");
       jButton1_OK.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1_OKActionPerformed(evt);
           }
       });

       jTextField1_CANTIDAD.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField1_CANTIDADActionPerformed(evt);
           }
       });

       jLabel3_CANTIDAD.setText("CANTIDAD");

       jButton2_CANCELAR.setText("CANCELAR");
       jButton2_CANCELAR.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2_CANCELARActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jComboBox1_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1_PRODUCTO))
               .addGap(75, 75, 75)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel3_CANTIDAD)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addComponent(jTextField1_CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                       .addComponent(jButton2_CANCELAR)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jButton1_OK)
               .addContainerGap())
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel2)
               .addGap(178, 178, 178))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(10, 10, 10)
               .addComponent(jLabel2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel1_PRODUCTO)
                           .addComponent(jLabel3_CANTIDAD))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jComboBox1_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField1_CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(28, 28, 28))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jButton1_OK)
                           .addComponent(jButton2_CANCELAR))
                       .addContainerGap())))
       );

       pack();
   }// </editor-fold>                        

   private void jTextField1_CANTIDADActionPerformed(java.awt.event.ActionEvent evt) {                                                     
       // TODO add your handling code here:
   }                                                    

   private void jButton2_CANCELARActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // TODO add your handling code here:
   }                                                 

   private void jButton1_OKActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
	  this.jLabel3_CANTIDAD.setText("Stock .l.");
	   
   }                                           

   private void jComboBox1_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {                                                     
       // TODO add your handling code here:
	   try {
		   int y=this.jComboBox1_PRODUCTOS.getSelectedIndex();
		   for(int i=0;i<=y;i++) {
			this.jLabel3_CANTIDAD.setText("CANTIDAD DISPONIBLE:"+ FacturaC.listarproductos().get(i).getStock());
		   }
		   } catch (SQLException e) {
			// TODO Bloque catch generado automáticamente
			e.printStackTrace();
		}

   }                                                    

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new AgregarProducto().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1_OK;
   private javax.swing.JButton jButton2_CANCELAR;
   private javax.swing.JComboBox<String> jComboBox1_PRODUCTOS;
   private javax.swing.JLabel jLabel1_PRODUCTO;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3_CANTIDAD;
   private javax.swing.JTextField jTextField1_CANTIDAD;
   // End of variables declaration                   
}
