package Vista;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import Controlador.ControladorFactura;
import Modelo.Producto;

/**
*
* @author JOSE
*/
public class QuitarProducto extends javax.swing.JFrame {

   /**
    * Creates new form AgregarProducto
    */
	private ControladorFactura FacturaC;
	private static String xyz=null;
	private ArrayList<Producto> b = new ArrayList<Producto>();
   public QuitarProducto(String xz) {
       initComponents();
       setSize(600,200);
       FacturaC=new ControladorFactura();
       xyz=xz;
       
       /** AQUI ES DONDE SE LLENA LA LISTA DE PRODUCTOS PERO DONDE ESTA EL GET ESTA UN 1 ES EL
       ESTOY MIRANDO COMO RECORRERLO Y QUE SE LLENE TODA LA LISTA ENTONCES, AGREGA UN ITEM
       DE EL METODO listarproductos DE EL CONTROLADOR Y TIENE UN CONTRO DE EXCEPCIONES PORQUE
       BIENE DEL TIPO DE CONEXION DE SQL.
       Esta en esta parte porque para que se llene el combo box, se llena cuando se inicia la
       ventana.
       
       */
       
       this.jComboBox1_PRODUCTOS.removeAllItems();
	   try {
		   for(int i=0;i<FacturaC.listarproductos(xyz).size();i++) {
			this.jComboBox1_PRODUCTOS.addItem(FacturaC.listarproductos(xyz).get(i).getNombre());
			Producto a=new Producto(FacturaC.listarproductos(xyz).get(i).getCodigo(),
					FacturaC.listarproductos(xyz).get(i).getNombre(), FacturaC.listarproductos(xyz).get(i).getValorUnitario(),FacturaC.listarproductos(xyz).get(i).getStock());
			b.add(a);
		   }
		   } catch (SQLException e) {
			// TODO Bloque catch generado automáticamente
			e.printStackTrace();
		}
   }


   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jComboBox1_PRODUCTOS = new javax.swing.JComboBox<>();
       jLabel1_PRODUCTO = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jButton1_OK = new javax.swing.JButton();
       jButton2_CANCELAR = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jComboBox1_PRODUCTOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       jComboBox1_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox1_PRODUCTOSActionPerformed(evt);
           }
       });

       jLabel1_PRODUCTO.setText("PRODUCTO");

       jLabel2.setText("ELIMINAR PRODUCTOS");

       jButton1_OK.setText("OK");
       jButton1_OK.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1_OKActionPerformed(evt);
           }
       });

       jButton2_CANCELAR.setText("CANCELAR");
       jButton2_CANCELAR.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2_CANCELARActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(67, 67, 67)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jComboBox1_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1_PRODUCTO))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addGap(18, 180, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jButton2_CANCELAR)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jButton1_OK)
                       .addContainerGap())
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jLabel2)
                       .addGap(178, 178, 178))))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(10, 10, 10)
               .addComponent(jLabel2)
               .addGap(22, 22, 22)
               .addComponent(jLabel1_PRODUCTO)
               .addGap(18, 18, 18)
               .addComponent(jComboBox1_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton1_OK)
                   .addComponent(jButton2_CANCELAR))
               .addContainerGap())
       );

       pack();
   }// </editor-fold>                        

   private void jButton2_CANCELARActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // TODO add your handling code here:
   }                                                 

   private void jButton1_OKActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
	   int a=this.jComboBox1_PRODUCTOS.getSelectedIndex();
	   
	   try {
		FacturaC.AProducto("1", xyz, Integer.toString(b.get(a).getCodigo()),"10");
	} catch (SQLException e) {
		// TODO Bloque catch generado automáticamente
		e.printStackTrace();
	}
		System.out.println(a);
	   this.dispose(); 
		  
			
   }                                           

   private void jComboBox1_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {                                                     
       // TODO add your handling code here:
   }                                                    

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new QuitarProducto(xyz).setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1_OK;
   private javax.swing.JButton jButton2_CANCELAR;
   private javax.swing.JComboBox<String> jComboBox1_PRODUCTOS;
   private javax.swing.JLabel jLabel1_PRODUCTO;
   private javax.swing.JLabel jLabel2;
   // End of variables declaration                   
}
